repoLabels:

  - name: bug
    color: ee1111
    description: Something isn't working

  - name: documentation
    color: 0e8a16
    description: Improvements or additions to the documentation

  - name: enhancement
    color: a2eeef
    description: New feature or request
